# Generated by Django 3.0.3 on 2020-10-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20201003_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
